import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f1f5f9" },
  filterIconButton: {
    width: 42,
    height: 42,
    borderRadius: 7,
    backgroundColor: "#064E3B",
    alignItems: "center",
    justifyContent: "center",
  },
  sectionBox: {
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#dbe5ef",
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#f8fafc",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  sectionHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  sectionLabel: {
    color: "#8aa0bd",
    fontSize: 11,
    fontWeight: "900",
    marginBottom: 10,
  },
  bulkText: { color: "#075e54", fontSize: 11, fontWeight: "900" },
  bulkTextMuted: { color: "#64748b", fontSize: 11, fontWeight: "900" },
  fieldGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  fieldChip: {
    width: "48%",
    minHeight: 36,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: "#075e54",
    backgroundColor: "#fff",
    paddingHorizontal: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  fieldText: {
    flex: 1,
    color: "#075e54",
    fontSize: 11,
    fontWeight: "900",
  },
  fieldChipActive: { backgroundColor: "#e2f3ee" },
  checkBox: {
    width: 14,
    height: 14,
    borderRadius: 3,
    borderWidth: 1,
    borderColor: "#075e54",
    alignItems: "center",
    justifyContent: "center",
  },
  checkBoxActive: { backgroundColor: "#075e54" },

  /* ============ Filter drawer ============ */
  filterSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 10,
    paddingBottom: 20,
    paddingHorizontal: 16,
    maxHeight: "85%",
  },
  filterSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
    paddingHorizontal: 2,
  },
  filterSheetTitle: {
    color: "#0F172A",
    fontSize: 17,
    fontWeight: "900",
  },
  filterSheetClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F5F9",
  },
  filterSheetBody: {
    paddingBottom: 14,
  },
  filterApplyButton: {
    height: 46,
    borderRadius: 8,
    backgroundColor: "#087568",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  filterApplyText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "900",
  },

  /* ============ Side / bottom menu ============ */
  menuBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.45)",
    justifyContent: "flex-end",
  },
  menuSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingTop: 10,
    paddingBottom: 24,
    paddingHorizontal: 16,
  },
  menuHandle: {
    alignSelf: "center",
    width: 44,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#cbd5e1",
    marginBottom: 14,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
  },
  menuIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#e2f3ee",
    alignItems: "center",
    justifyContent: "center",
  },
  menuIconWrapDanger: {
    backgroundColor: "#fee2e2",
  },
  menuCopy: { flex: 1 },
  menuTitle: {
    color: "#020617",
    fontSize: 14,
    fontWeight: "900",
  },
  menuTitleDanger: { color: "#b91c1c" },
  menuSubtitle: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  menuDivider: {
    height: 1,
    backgroundColor: "#e2e8f0",
    marginVertical: 6,
  },
});
